use_frameworks!

platform :ios, '9.0'

target 'TWFoundation_Example' do
  pod 'TWFoundation', :path => '../'

  target 'TWFoundation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
